#!/bin/sh
TESTFILE=tmptest.txt
PROG=${1:-./lunamark.lua}
NUM=${2:-25}
rm $TESTFILE
x=$NUM
while [ $x -gt 0 ]
do
    sed -e '1,/<<</d' -e '/>>>/,$d' tests/Markdown_1.0.3/Markdown\ Documentation\ -\ Syntax.test >> $TESTFILE
    x=$(($x-1))
done
time $PROG < $TESTFILE > /dev/null
du -h $TESTFILE
