#!/bin/sh
rm -rf doc
mkdir doc
bin/lunadoc lunamark.lua lunamark/*.lua lunamark/*/*.lua
version=`bin/lunamark --version | head -1`
date=`date +'%F'`
bin/lunamark --man | bin/lunamark -Xall -t man -s -d section=1,title=lunamark,center_header="$version",date="$date" -o lunamark.1
