name: Release a new version
on:
  push:
    tags:
      - '*.*.*'

jobs:
  luarocks-release:
    name: Upload to luarocks
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install luarocks
        run: >-
          sudo apt install luarocks lua-dkjson

      - name: Upload rock and rockspec
        run: |
          luarocks upload lunamark-${{ github.ref_name }}-1.rockspec --api-key=${{ secrets.API_KEY }}
